
== 配置 Configuration

[[configuration]]

=== 创建一个DMN引擎 Creating a DMN Engine

__Flowable DMN引擎的结构与Flowable流程引擎十分相似。因此，本文档的部分内容与流程引擎的对应部分也十分相似。__

Flowable DMN引擎使用一个名为++flowable.dmn.cfg.xml++的XML文件配置。请注意在使用<<springintegration,Sping方式创建DMN引擎>>的情况下不是这样。

得到++DmnEngine++最简单的方法，是使用++org.flowable.dmn.engine.DmnEngines++类：

[source,java,linenums]
----
DmnEngine dmnEngine = DMNEngines.getDefaultDmnEngine()
----

这样会在classpath中查找++flowable.dmn.cfg.xml++文件，并使用这个文件中的配置创建一个引擎。下面的代码片段展示了一个配置的例子。之后的章节将详细介绍各配置参数。

[source,xml,linenums]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

  <bean id="dmnEngineConfiguration" class="org.flowable.dmn.engine.impl.cfg.StandaloneDmnEngineConfiguration">

    <property name="jdbcUrl" value="jdbc:h2:mem:flowable;DB_CLOSE_DELAY=1000" />
    <property name="jdbcDriver" value="org.h2.Driver" />
    <property name="jdbcUsername" value="sa" />
    <property name="jdbcPassword" value="" />

    <property name="databaseSchemaUpdate" value="true" />

  </bean>

</beans>
----

请注意这个配置XML实际上是一个Spring配置文件。**但这并不意味着Flowable DMN只能用于Spring环境！**我们只是简单利用Spring内部的解析与依赖注入功能来构造引擎。

也可以通过编程方式使用配置文件，来构造DMNEngineConfiguration对象。也可以使用不同的bean id(例如第3行)。

[source,java,linenums]
----
DmnEngineConfiguration.
  createDmnEngineConfigurationFromResourceDefault();
  createDmnEngineConfigurationFromResource(String resource);
  createDmnEngineConfigurationFromResource(String resource, String beanName);
  createDmnEngineConfigurationFromInputStream(InputStream inputStream);
  createDmnEngineConfigurationFromInputStream(InputStream inputStream, String beanName);
----

也可以不使用配置文件，基于默认创建配置（参考<<configurationClasses,不同的支持类>>获得更多信息）。

[source,java,linenums]
----
DmnEngineConfiguration.createStandaloneDmnEngineConfiguration();
DmnEngineConfiguration.createStandaloneInMemDmnEngineConfiguration();
----


所有的++DmnEngineConfiguration.createXXX()++方法都返回++DmnEngineConfiguration++，并可以继续按需调整。调用++buildDmnEngine()++后，生成一个++DmnEngine++：

[source,java,linenums]
----
DmnEngine dmnEngine = DmnEngineConfiguration.createStandaloneInMemDmnEngineConfiguration()
  .setDatabaseSchemaUpdate(DmnEngineConfiguration.DB_SCHEMA_UPDATE_FALSE)
  .setJdbcUrl("jdbc:h2:mem:my-own-db;DB_CLOSE_DELAY=1000")
  .buildDmnEngine();
----

[[configurationRoot]]


=== DmnEngineConfiguration bean

++flowable.dmn.cfg.xml++文件中必须包含一个id为$$'dmnEngineConfiguration'$$的bean。


[source,xml,linenums]
----
 <bean id="dmnEngineConfiguration" class="org.flowable.dmn.engine.impl.cfg.StandaloneDmnEngineConfiguration">
----


这个bean用于构建++DmnEngine++。有多个类可以用于定义++dmnEngineConfiguration++。这些类用于不同的环境，并各自设置一些默认值。最佳实践是选择最匹配你环境的类，以便减少配置引擎需要的参数。下面列出目前可以使用的类：[[configurationClasses]]

* *org.flowable.dmn.engine.impl.cfg.StandaloneDmnEngineConfiguration*: 流程引擎独立运行。Flowable自行处理事务。在默认情况下，数据库检查只在引擎启动时进行（如果Flowable DMN表结构不存在或表结构版本不对，会抛出异常）。
* *org.flowable.dmn.engine.impl.cfg.StandaloneInMemDmnEngineConfiguration*: 这是一个便于使用单元测试的类。Flowable DMN自行处理事务。默认使用H2内存数据库。数据库会在引擎启动时创建，并在引擎关闭时删除。使用这个类时，很可能不需要更多的配置。
* *org.flowable.dmn.spring.SpringDmnEngineConfiguration*: 在流程引擎处于Spring环境时使用。查看<<springintegration,Spring集成章节>>获得更多信息。

=== 插入流程引擎 Plug into Process Engine

除了在独立模式下运行之外，也可能需要将DMN引擎插入流程引擎中。这样可以使流程引擎能够使用DMN和其他引擎。这样就可以，例如，让流程引擎的部署服务API可以部署的包中，不止包含BPMN模型，还可以包含DMN模型。

要在流程引擎中使用DMN引擎，需要在流程引擎配置文件的configurators列表中，添加**org.flowable.dmn.engine.configurator.DmnEngineConfigurator**。

[source,xml,linenums]
----
<bean id="dmnEngineConfiguration" class="org.flowable.dmn.engine.impl.cfg.StandaloneDmnEngineConfiguration">
    <property name="jdbcUrl" value="jdbc:h2:mem:flowable;DB_CLOSE_DELAY=1000" />
    <property name="jdbcDriver" value="org.h2.Driver" />
    <property name="jdbcUsername" value="sa" />
    <property name="jdbcPassword" value="" />
    ...
</bean>

<bean id="dmnEngineConfigurator" class="org.flowable.dmn.engine.configurator.DmnEngineConfigurator">
    <property name="dmnEngineConfiguration" ref="dmnEngineConfiguration" />
</bean>

<bean id="processEngineConfiguration" class="org.flowable.engine.impl.cfg.StandaloneProcessEngineConfiguration">
    <property name="configurators">
      <list>
        <ref bean="dmnEngineConfigurator" />
      </list>
    </property>
    ...
</bean>
----


[[databaseConfiguration]]

=== 数据库配置 Database configuration

有两种方式配置Flowable DMN引擎使用的数据库。第一种方式是定义数据库的JDBC参数：

* *jdbcUrl*: 数据库的JDBC URL。
* *jdbcDriver*: 特定数据库类型的驱动实现。
* *jdbcUsername*: 用于连接数据库的用户名。
* *jdbcPassword*: 用于连接数据库的密码。

通过提供的JDBC参数构造的数据源，使用默认的link:$$http://www.mybatis.org/$$[MyBatis]连接池设置。可用下列属性调整这个连接池（来自MyBatis文档）：

* *jdbcMaxActiveConnections*: 连接池能够容纳的最大活动连接数量。默认值为10.
* *jdbcMaxIdleConnections*: 连接池能够容纳的最大空闲连接数量。
* *jdbcMaxCheckoutTime*: 连接从连接池“取出”后，被强制返回前的最大时间间隔，单位为毫秒。默认值为20000（20秒）。
* *jdbcMaxWaitTime*: 这是一个底层设置，在连接池获取连接的时间异常长时，打印日志并尝试重新获取连接（避免连接池配置错误造成的永久沉默失败。默认值为20000（20秒）。

数据库配置示例：

[source,xml,linenums]
----
<property name="jdbcUrl" value="jdbc:h2:mem:flowable_dmn;DB_CLOSE_DELAY=1000" />
<property name="jdbcDriver" value="org.h2.Driver" />
<property name="jdbcUsername" value="sa" />
<property name="jdbcPassword" value="" />
----

我们的跑分显示MyBatis连接池在处理大量并发请求时，并不是最经济或最具弹性的。因此，建议使用++javax.sql.DataSource++的实现，并将其注入到流程引擎配置中（例如DBCP、CP30、Hikari、Tomcat连接池，等等）：

[source,xml,linenums]
----
<bean id="dataSource" class="org.apache.commons.dbcp.BasicDataSource" >
  <property name="driverClassName" value="com.mysql.jdbc.Driver" />
  <property name="url" value="jdbc:mysql://localhost:3306/flowable_dmn" />
  <property name="username" value="flowable" />
  <property name="password" value="flowable" />
  <property name="defaultAutoCommit" value="false" />
</bean>

<bean id="dmnEngineConfiguration" class="org.flowable.dmn.engine.impl.cfg.StandaloneDmnEngineConfiguration">

    <property name="dataSource" ref="dataSource" />
    ...

----

请注意Flowable DMN发布时不包括用于定义数据源的库。需要自行把库放在你的classpath中。

无论使用JDBC还是数据源方式配置，下列参数都可以使用：

* *databaseType*: 通常不需要专门设置这个参数，因为它可以从数据库连接信息中自动检测得出。只有在自动检测失败时才需要设置。可用值：{h2, mysql, oracle, postgres, mssql, db2}。这个选项会决定创建、删除与查询时使用的脚本。查看<<supporteddatabases,“支持的数据库”章节>>了解我们支持哪些类型的数据库。
* *databaseSchemaUpdate*: 用于设置流程引擎启动关闭时使用的数据库表结构控制策略。
** +false+ (默认): 当引擎启动时，检查数据库表结构的版本是否匹配库文件版本。版本不匹配时抛出异常。
** ++true++: 构建引擎时，检查并在需要时更新表结构。表结构不存在则会创建。
** ++create-drop++: 引擎创建时创建表结构，并在引擎关闭时删除表结构。


[[jndiDatasourceConfig]]

=== JNDI数据源配置 JNDI Datasource Configuration

默认情况下，Flowable DMN的数据库配置保存在每个web应用WEB-INF/classes目录下的db.properties文件中。有时这样并不合适，因为这需要用户修改Flowable源码中的db.properties文件并重新编译war包，或者在部署后解开war包并修改db.properties文件。

通过使用JNDI（Java Naming and Directory Interface，Java命名和目录接口）获取数据库连接时，连接就完全由Servlet容器管理，并可以在war部署之外管理配置。同时也提供了比db.properties中更多的控制连接的参数。


[[jndi_configuration]]

==== 配置 Configuration

根据你使用的servlet容器应用不同，配置JNDI数据源的方式也不同。下面的介绍用于Tomcat，对于其他容器应用，请参考对应的文档。

Tomcat的JNDI资源配置在$CATALINA_BASE/conf/[enginename]/[hostname]/[warname].xml (对于Flowable UI应用，通常会是$CATALINA_BASE/conf/Catalina/localhost/flowable-app.xml)。当应用第一次部署时，默认会从Flowable war包中复制context.xml。所以如果存在这个文件则需要替换。例如，如果需要将JNDI资源修改为应用连接MySQL而不是H2，按照下列修改文件：

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
    <Context antiJARLocking="true" path="/flowable-app">
        <Resource auth="Container"
            name="jdbc/flowableDB"
            type="javax.sql.DataSource"
            description="JDBC DataSource"
            url="jdbc:mysql://localhost:3306/flowable"
            driverClassName="com.mysql.jdbc.Driver"
            username="sa"
            password=""
            defaultAutoCommit="false"
            initialSize="5"
            maxWait="5000"
            maxActive="120"
            maxIdle="5"/>
        </Context>
----


==== JNDI参数 JNDI properties

要配置JNDI数据源，在Flowable UI应用的配置文件中使用下列参数：

* datasource.jndi.name: 数据源的JNDI名
* datasource.jndi.resourceRef: 设置是否在J2EE容器中查找。也就是说，如果JNDI名中没有包含"java:comp/env/"前缀，是否需要添加它。默认为"true"。


[[supporteddatabases]]


=== 支持的数据库 Supported databases

下面列出Flowable用于引用数据库的类型（区分大小写！）。

[[databaseTypes]]
[options="header"]
|===============
|Flowable DMN数据库类型|示例JDBC URL|备注
|h2|jdbc:h2:tcp://localhost/flowable_dmn|默认配置的数据库
|mysql|jdbc:mysql://localhost:3306/flowable_dmn?autoReconnect=true|已使用mysql-connector-java数据库驱动测试
|oracle|jdbc:oracle:thin:@localhost:1521:xe|
|postgres|jdbc:postgresql://localhost:5432/flowable_dmn|
|db2|jdbc:db2://localhost:50000/flowable_dmn|
|mssql|jdbc:sqlserver://localhost:1433;databaseName=flowable_dmn (jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver) __或__ jdbc:jtds:sqlserver://localhost:1433/flowable_dmn (jdbc.driver=net.sourceforge.jtds.jdbc.Driver)|已使用Microsoft JDBC Driver 4.0 (sqljdbc4.jar)与JTDS Driver测试
|===============

[[creatingDatabaseTable]]

=== 创建数据库表 Creating the database tables

Flowable DMM使用link:$$http://www.liquibase.org$$[Liquibase]追踪、管理与应用数据库表结构变更。

在你的数据库中创建数据库表，最简单的方法是：

* 在classpath中增加flowable-dmn-engine JAR
* 增加合适的数据库驱动
* 在classpath中增加Flowable配置文件(__flowable.dmn.cfg.xml__)，指向你的数据库(参考<<databaseConfiguration,数据库配置>>)
* 执行__DbSchemaCreate__类的main方法

[[database.tables.explained]]


=== 数据库表名说明 Database table names explained

Flowable DMN的所有数据库表都以**ACT_DMN_**开头。

* ACT_DMN_DATABASECHANGELOG: 由Liquibase使用，用于追踪表结构修改。
* ACT_DMN_DATABASECHANGELOGLOCK: 由Liquibase使用，用于确保同时只有一个运行的Liquibase实例。
* ACT_DMN_DECISION_TABLE: 保存已部署的选择表的元数据。
* ACT_DMN_DEPLOYMENT: 保存部署的元数据。
* ACT_DMN_DEPLOYMENT_RESOURCE: 保存DMN定义的资源和元数据。

[[databaseUpgrade]]


=== 数据库升级 Database upgrade

在升级前，请确保你已经（使用数据库的备份功能）备份了数据库。

默认情况下，每次流程引擎创建时会进行版本检查，通常是在你的应用或者Flowable web应用启动的时候。如果Flowable库发现库版本与Flowable数据库表版本不同，会抛出异常。

要进行升级，首先需要将下列配置参数放入你的flowable.dmn.cfg.xml配置文件：

[source,xml,linenums]
----
<beans >

  <bean id="dmnEngineConfiguration" class="org.flowable.dmn.engine.impl.cfg.StandaloneDmnEngineConfiguration">
    <!-- ... -->
    <property name="databaseSchemaUpdate" value="true" />
    <!-- ... -->
  </bean>

</beans>
----

**同时，在classpath中加上合适的数据库驱动。**升级你应用中的Flowable DMN库，或者启动一个新版本的Flowable DMN，并将它指向包含旧版本数据的数据库。将++databaseSchemaUpdate++设置为++true++。当Flowable DMN发现库与数据库表结构不同步时，会自动将数据库表结构升级至新版本。

[[processDefinitionCacheConfiguration]]


=== 配置部署缓存 Deployment cache configuration

鉴于选择表信息不会改变，为了避免每次使用选择表时都读取数据库，所有的选择配置都会（在解析后）被缓存。默认情况下，这个缓存没有限制。要限制选择缓存，加上如下的参数


[source,xml,linenums]
----
<property name="decisionCacheLimit" value="10" />
----

设置这个参数，会将默认的hashmap替换为LRU缓存，以进行限制。当然，参数的“最佳”取值，取决于总的选择定义数量，以及实际使用的选择定义数量。

你也可以注入自己的缓存实现。它必须是一个实现了org.flowable.dmn.engine.impl.persistence.deploy.DeploymentCache接口的bean：

[source,xml,linenums]
----
<property name="decisionCache">
  <bean class="org.flowable.MyCache" />
</property>
----


[[loggingConfiguration]]


=== 日志 Logging

所有的日志（Flowable、Spring、MyBatis等）都通过SLF4J路由，并允许你自行选择日志实现。

**默认情况下，Flowable引擎依赖中不提供SFL4J绑定jar。你需要自行将其加入你的项目，以便使用所选的日志框架。**如果没有加入实现jar，SLF4J会使用NOP-logger。这时除了一条警告外，不会记录任何日志。可以从link:$$http://www.slf4j.org/codes.html#StaticLoggerBinder$$[http://www.slf4j.org/codes.html#StaticLoggerBinder]了解关于绑定的更多信息。

可以像这样（这里使用Log4j）使用Maven添加依赖，请注意你还需要加上版本：

[source,xml,linenums]
----
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-log4j12</artifactId>
</dependency>
----


Flowable-UI与Flowable-rest web应用配置为使用Log4j绑定。运行所有flowable-*模块的测试时也会使用Log4j。

**重要提示：当使用classpath中带有commons-logging的容器时：**为了将spring的日志路由至SLF4j，需要使用桥接（参考link:$$http://www.slf4j.org/legacy.html#jclOverSLF4J$$[http://www.slf4j.org/legacy.html#jclOverSLF4J]）。如果你的容器提供了commons-logging实现，请按照link:$$http://www.slf4j.org/codes.html#release$$[http://www.slf4j.org/codes.html#release]页面的指示来保证稳定性。

使用Maven的示例（省略了版本）：

[source,xml,linenums]
----
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>jcl-over-slf4j</artifactId>
</dependency>
----
