[[chapterApi]]

== The Flowable DMN API

[[apiEngine]]


=== DMN引擎API与服务 The DMN Engine API and services

DMN引擎API是与Flowable DMN交互的最常用手段。其入口是++DmnEngine++，并像<<configuration,配置章节>>中介绍的一样，可以使用多种方式创建。使用DmnEngine，可以获得各种其他服务。DmnEngine与服务对象都是线程安全的，因此可以在整个服务器中保存一份引用。

[source,java,linenums]
----
DmnEngine dmnEngine = DmnEngines.getDefaultDmnEngine();
DmnRuleService dmnRuleService = dmnEngine.getDmnRuleService();
DmnRepositoryService dmnRepositoryService = dmnEngine.getDmnRepositoryService();
DmnManagementService dmnManagementService = dmnEngine.getDmnManagementService();
----

++DmnEngines.getDefaultDmnEngine()++在第一次被调用时将初始化并构建DMN引擎，在之后的调用都会返回相同的DMN引擎。DMN引擎的创建通过++DMNEngines.init()++实现，关闭由++DMNEngines.destroy()++实现。

DmnEngines会扫描所有++flowable.dmn.cfg.xml++与++flowable-dmn-context.xml++文件。对于所有的++flowable.dmn.cfg.xml++文件，DMN引擎会以标准Flowable方式构建引擎：++DmnEngineConfiguration.createDmnEngineConfigurationFromInputStream(inputStream).buildDmnEngine()++。对于所有的++flowable-dmn-context.xml++文件，DMN引擎会以Spring的方式构建：首先构建Spring应用上下文，然后从该上下文中获取DMN引擎。

所有的服务都是无状态的。这意味着你可以很容易的在集群环境的多个节点上运行Flowable DMN，使用同一个数据库，而不用担心上一次调用实际在哪台机器上执行。不论在哪里执行，对任何服务的任何调用都是幂等（idempotent）的。

**DmnRepositoryService**很可能是使用Flowable DMN引擎要用的第一个服务。这个服务提供了管理与控制++部署(deployments)++与++DMN定义(DMN definitions)++的操作。DMN定义是DMN模型的基础概念(DMN的主要概念在<<dmn-introduction, DMN介绍章节>>中介绍)。它包含了++选择(decision)++以及对应的++选择表(decision table)++。++部署(deployment)++是Flowable DMN引擎中的包装单元，一个部署中可以包含多个DMN XML文件。部署意味着将它上传至引擎，引擎将在储存至数据库之前检查与分析所有的DMN定义。从这里开始，可以在系统中使用这个部署，部署中包含的所有选择都可以使用。

此外，这个服务还可以：

* 查询引擎已知的部署、DMN定义与选择表。
* 获取POJO版本的DMN定义或选择表。使用它可以用Java而不是XML的方式检查选择。

**DmnRuleService**提供执行选择的方法。提供参数和输入参数，就可以开始计算选择。

**DmnManagementService**通常在用Flowable DMN编写用户应用时不需要使用。它可以获取关于引擎版本、数据库表以及数据库内容的信息。

参考link:$$http://flowable.org/javadocs/index.html$$[javadocs]了解服务操作与DMN引擎API的更多信息。

=== 异常策略 Exception strategy

Flowable的异常基类是++org.flowable.engine.FlowableException++，这是一个未检查异常(unchecked exception)。在任何API操作时都可能会抛出这个异常，link:$$http://flowable.org/javadocs/index.html$$[javadoc]记录了每个方法可能发生的异常。例如，从++DmnRuleService++中摘录：

[source,java,linenums]
----
/**
  * 按照key查找并执行一个选择。 --Execute a decision identified by it's key.
  *
  * @param  decisionKey      选择的key，不能为null。  --the decision key, cannot be null
  * @param  inputVariables   包含输入变量的map。  --map with input variables
  * @return                  执行的{@link RuleEngineExecutionResult}。  --the {@link RuleEngineExecutionResult} for this execution
  * @throws FlowableObjectNotFoundException
  *            如果给定key不存在。  --when the decision with given key does not exist.
  * @throws FlowableException
  *            如果执行选择时发生错误。  --when an error occurs while executing the decision.
  */
RuleEngineExecutionResult executeDecisionByKey(String decisionKey, Map<String, Object> inputVariables);
----

在上例中，如果传递的key找不到选择，会抛出异常。并且，由于javadoc中**明确要求decisionKey不能为null，因此如果传递了++null++值，会抛出++FlowableIllegalArgumentException++异常**。

尽管我们想避免过大的异常层次结构，在特定情况下仍然会抛出下述异常子类。所有流程执行与API调用中发生的错误，如果不符合下面列出的异常，会统一抛出++FlowableExceptions++。

* ++FlowableOptimisticLockingException++: 当对同一数据实体的并发访问，导致数据存储发生乐观锁时抛出。
* ++FlowableClassLoadingException++: 当需要载入的类（如JavaDelegates, TaskListeners, ...）无法找到，或载入时发生错误时抛出。
* ++FlowableObjectNotFoundException++: 当请求或要操作的对象不存在时抛出。
* ++FlowableIllegalArgumentException++: 这个异常说明调用Flowable DMN API时使用了不合法的参数。可能是引擎配置中的不合法值，或者是API调用传递的不合法参数。

[[queryAPI]]


=== 查询API (Query API)

从引擎中查询数据有两种方式：查询API与原生(native)查询。查询API可以使用链式API，通过编程方式进行类型安全的查询。你可以在查询中增加各种条件（所有条件都用做AND逻辑），也可以明确指定排序。下面是示例代码：

[source,java,linenums]
----
List<DmnDeployment> dmnDeployments = dmnRepositoryService.createDeploymentQuery()
    .deploymentNameLike("deployment%")
    .orderByDeployTime()
    .list();
----

有时你需要更强力的查询，例如使用OR操作符查询，或者使用查询API不能满足查询条件要求。我们为这种需求提供了可以自己写SQL查询的原生查询。返回类型由使用的查询对象决定，数据也会映射到正确的对象中（Task、ProcessInstance、Execution，等等）。查询会在数据库中进行，因此你需要使用数据库中定义的表名与列名。这需要了解内部数据结构，因此建议小心使用原生查询。数据库表名可以通过API读取，这样可以将依赖关系减到最小。

[source,java,linenums]
----

long count = dmnRepositoryService.createNativeDeploymentQuery()
    .sql("SELECT count(*) FROM " + dmnManagementService.getTableName(DmnDeploymentEntity.class) + " D1, "
        + dmnManagementService.getTableName(DecisionTableEntity.class) + " D2 "
        + "WHERE D1.ID_ = D2.DEPLOYMENT_ID_ "
        + "AND D1.ID_ = #{deploymentId}")
    .parameter("deploymentId", deployment.getId())
    .count();
----

[[apiUnitTesting]]


=== 单元测试 Unit testing

Flowable是嵌入式的Java引擎，因此为业务流程编写单元测试就与编写一般的单元测试一样简单。

Flowable支持JUnit V4的单元测试风格。撰写JUnit 4测试用例时，可以使用++org.flowable.dmn.engine.test.FlowableDmnRule++ Rule。使用这个Rule，就可以通过getter访问DMN引擎和服务。引入这个++Rule++就可以使用++org.flowable.dmn.engine.test.DmnDeploymentAnnotation++注解（参见上例解释其用途及配置），并且会自动在classpath中寻找默认配置文件。当使用相同的配置资源时，流程引擎会静态缓存，以用于多个单元测试。也可以为Rule提供自定义的引擎配置。

下面的代码片段展示了JUnit 4风格的测试与++FlowableDmnRule++的用法（并传入了一个可选的自定义配置）：

[source,java,linenums]
----
public class MyDecisionTableTest {

  @Rule
  public FlowableDmnRule flowableDmnRule = new FlowableDmnRule("custom1.flowable.dmn.cfg.xml");

  @Test
  @DmnDeploymentAnnotation
  public void ruleUsageExample() {
    DmnEngine dmnEngine = flowableDmnRule.getDmnEngine();
    DmnRuleService dmnRuleService = dmnEngine.getDmnRuleService();

    Map<String, Object> inputVariables = new HashMap<>();
    inputVariables.put("inputVariable1", 2);
    inputVariables.put("inputVariable2", "test2");

    RuleEngineExecutionResult result = dmnRuleService.executeDecisionByKey("decision1", inputVariables);

    Assert.assertEquals("result2", result.getResultVariables().get("outputVariable1"));
  }
}
----


[[apiProcessEngineInWebApp]]


=== Web应用中的DMN引擎 The DMN engine in a web application

++DmnEngine++是线程安全的类，可以很容易地在多个线程间共享。在web应用中，这意味着可以在容器启动时创建DMN引擎，并在容器关闭时关闭引擎。

下面的代码片段展示了如何在纯Servlet环境中，简单的通过++ServletContextListener++初始化与销毁流程引擎。

[source,java,linenums]
----
public class DmnEnginesServletContextListener implements ServletContextListener {

  public void contextInitialized(ServletContextEvent servletContextEvent) {
    DmnEngines.init();
  }

  public void contextDestroyed(ServletContextEvent servletContextEvent) {
    DmnEngines.destroy();
  }

}
----

++contextInitialized++方法会调用++ProcessEngines.init()++。它会在classpath中查找++flowable.dmn.cfg.xml++资源文件，并为每个配置分别创建++DmnEngine++（例如多个JAR都包含配置文件）。如果在classpath中有多个这样的资源文件，请确保它们都使用不同的名字。需要使用DMN引擎时，可以获取通过：

[source,java,linenums]
----
DmnEngines.getDefaultDmnEngine()
----

或者：

[source,java,linenums]
----
DmnEngines.getDmnEngine("myName");
----

当然，就像<<configuration,配置章节>>中介绍的，还可以使用各种不同的方式创建DMN引擎。

context-listener的++contextDestroyed++方法会调用++ProcessEngines.destroy()++。它会妥善关闭所有已初始化的流程引擎。