[[springintegration]]

== 集成Spring (Spring integration)

尽管完全可以脱离Spring使用Flowable DMN，我们仍提供了很多非常好的集成特性，并将在这一章节介绍。

=== DmnEngineFactoryBean

++DmnEngine++可以被配置为普通的Spring bean。集成起点是++org.flowable.dmn.spring.DmnEngineFactoryBean++类。这个bean处理DMN引擎配置，并创建DMN引擎。这意味着在Spring中，创建与设置参数与<<configuration,配置章节 configuration section>>中介绍的一样。集成Spring的配置与引擎bean为：

[source,xml,linenums]
----
<bean id="dmnEngineConfiguration" class="org.flowable.dmn.spring.SpringDmnEngineConfiguration">
    ...
</bean>

<bean id="dmnEngine" class="org.flowable.dmn.spring.DmnEngineFactoryBean">
  <property name="dmnEngineConfiguration" ref="dmnEngineConfiguration" />
</bean>

----

请注意++dmnEngineConfiguration++ bean现在使用++org.flowable.dmn.spring.SpringDmnEngineConfiguration++类。

=== 自动部署资源 Automatic resource deployment

集成Spring还提供了部署资源的特殊方式。在DMN引擎配置中，可以指定一组资源。当DMN引擎被创建时，这些资源都会被扫描并部署。有过滤器用于阻止重复部署。只有当资源确实发生变化时，才会重新部署至Flowable DMN数据库。在Spring容器经常重启（例如测试时）的时候，这很有用。

这里有个例子：

[source,xml,linenums]
----
<bean id="dmnEngineConfiguration" class="org.flowable.spring.SpringDmnEngineConfiguration">
  ...
  <property name="deploymentResources"
    value="classpath*:/org/flowable/spring/test/autodeployment/autodeploy/decision*.dmn" />
</bean>

<bean id="dmnEngine" class="org.flowable.dmn.spring.DmnEngineFactoryBean">
  <property name="dmnEngineConfiguration" ref="dmnEngineConfiguration" />
</bean>
----

默认情况下，这个配置会将符合这个过滤器的所有资源组织在一起，作为Flowable DMN引擎的一个部署。重复检测过滤器将作用于整个部署，避免重复地部署未改变资源。有时这不是你想要的。例如，如果用这种方式部署了一组DMN资源，即使只有其中的一个资源发生了改变，整个部署都会被认为已经改变，因此这个部署中所有的所有DMN定义都会被重新部署。这将导致每个DMN定义都会刷新版本号，即使实际上只有一个DMN发生了变化。

可以使用++SpringDmnEngineConfiguration++中的额外参数+deploymentMode+，定制部署的选择方式。这个参数定义了在一组符合过滤器的资源中，组织部署的方式。默认这个参数有3个可用值：


* ++default++: 将所有资源组织在一个部署中，整体用于重复检测过滤。这是默认值，在未设置这个参数时也会用这个值。
* ++single-resource++: 为每个资源创建一个单独的部署，并用于重复检测过滤。当你希望单独部署每一个DMN定义，并且在它发生变化时创建新的DMN定义版本，应该使用这个值。
* ++resource-parent-folder++: 为同一个目录下的资源创建一个单独的部署，并用于重复检测过滤。这个参数值可以为大多数资源创建独立的部署。同时仍可以通过将部分资源放在同一个目录下，将它们组织在一起。这里有一个将++deploymentMode++设置为++single-resource++的例子：

[source,xml,linenums]
----
<bean id="dmnEngineConfiguration"
    class="org.flowable.dmn.spring.SpringDmnEngineConfiguration">
  ...
  <property name="deploymentResources" value="classpath*:/flowable/*.dmn" />
  <property name="deploymentMode" value="single-resource" />
</bean>
----

如果上述++deploymentMode++的参数值不能满足要求，还可以自定义组织部署的行为。可以创建++SpringDmnEngineConfiguration++的子类，并覆盖++getAutoDeploymentStrategy(String deploymentMode)++方法。这个方法决定了对于给定的++deploymentMode++参数值，使用何种部署策略。


[[springUnitTest]]


=== 单元测试 Unit testing

与Spring集成后，选择就可以非常简单地使用标准的 <<apiUnitTesting,Flowable测试工具 Flowable testing facilities>>进行测试。下面的例子展示了如何通过典型的基于Spring的单元测试，对选择进行测试：

[source,java,linenums]
----
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration("classpath:org/flowable/spring/test/junit4/springTypicalUsageTest-context.xml")
public class SpringJunit4Test {

    @Autowired
    private DmnEngine dmnEngine;

    @Autowired
    private DmnRuleService ruleService;

    @Autowired
    @Rule
    public FlowableDmnRule flowableSpringRule;

    @Test
    @DmnDeploymentAnnotation
    public void simpleDecisionTest() {
        Map<String, Object> inputVariables = new HashMap<>();
        inputVariables.put("input1", "testString");

        RuleEngineExecutionResult executionResult = ruleService.executeDecisionByKey("decision1", inputVariables);

        assertEquals("test1", executionResult.getResultVariables().get("output1"));
    }
}
----

请注意要让这个例子可以正常工作，需要在Spring配置中定义__org.flowable.dmn.engine.test.FlowableDmnRule__ bean（在上面的例子中通过auto-wiring注入）。

[source,xml,linenums]
----
<bean id="flowableDmnRule" class="org.flowable.dmn.engine.test.FlowableDmnRule">
    <property name="dmnEngine" ref="dmnEngine"/>
</bean>

----
