[[chDeployment]]

== 部署 Deployment


=== DMN定义 DMN Definitions

可以在DMN引擎中部署带有++.dmn++扩展名的DMN定义。

如果DMN引擎已经插入流程引擎，就可以与其他流程相关资源一起，将DMN定义打包进业务存档(BAR)文件中。流程引擎部署服务会将DMN资源部署至DMN引擎。

[NOTE]
====
业务存档中的Java类**不会添加至classpath**。业务存档中，所有选择使用的自定义类，都需要在用于运行选择的Flowable (DMN)引擎的classpath下。
====

==== DMN定义，选择及选择表 DMN Definitions, decisions and decision tables

DMN定义由选择(decision)和其他东西组成。选择有一个表达式。DMN标准描述了几种表达式的类型。目前在Flowable DMN中，我们支持选择表(decision table)类型的表达式。在部署DMN定义时，所有选择，每个可以包含一个**选择表**，将分别插入至ACT_DMN_DECISION表中。

==== 编程方式部署 Deploying programmatically

可以这样部署一个DMN定义：

[source,java,linenums]
----
String dmnDefinition = "path/to/definition-one.dmn";
ZipInputStream inputStream = new ZipInputStream(new FileInputStream(barFileName));

repositoryService.createDeployment()
    .name("definition-one")
    .addClasspathResource(dmnDefinition)
    .deploy();

----


==== Java类 Java classes

所有自定义表达式函数中用到的自定义类，在执行选择时，都需要存在于引擎的classpath中。

然而在部署DMN定义时，classpath中不是必须要有这些类。

当使用演示配置，且希望添加自定义类时，需要在flowable-ui-app或flowable-app-rest webapp的 lib中，添加包含有你的自定义类的JAR。别忘了也要添加你的自定义类的依赖（若有）。或者，也可以将你的依赖添加到Tomcat的库文件夹，++${tomcat.home}/lib++中。


==== 创建单独应用 Creating a single app

如果不想费心保证所有DMN引擎都在classpath中含有所有需要的代理类，以及保证它们都使用了正确的Spring配置，也可以考虑将flowable-rest web应用嵌入你自己的web应用，这样就只有一个单独的++DmnEngine++。

[[versioningOfDMNDefinitions]]


=== DMN选择的版本 Versioning of DMN decisions

DMN并没有版本的概念。这其实很好，因为可执行的DMN定义文件很可能已经作为你的开发项目的一部分，保存在版本管理系统仓库中了（例如Subversion，Git，或者Mercurial）。在部署时，会创建DMN定义的版本。在部署时，Flowable会在保存至Flowable数据库前，为++decision++指定版本。


对于DMN定义中的每个DMN选择，下列步骤都会执行，以初始化++key++、++version++、++name++与++id++参数：

* XML文件中选择的++id++属性作为选择表的++key++参数。
* XML文件中选择的++name++属性作为选择表的++name++参数。
* 当每个key的选择第一次部署时，指定版本为1。对其后所有使用相同key的选择，部署时版本会在该key当前已部署的最高版本号基础上加1。key参数用于区分选择。
* id参数是一个唯一数字，用以保证在集群环境下，选择表缓存中，选择表标识的唯一性。


以下面的选择为例：

[source,xml,linenums]
----
<definitions id="myDefinitions" >
  <decision id="myDecision" name="My important decision" >
    <decisionTable id="decisionTable1" hitPolicy="FIRST" >
    ...
----

当部署这个选择时，数据库中的选择表会是这个样子：

[options="header"]
|===============
|id|key|name|version
|e29d4126-ed4d-11e6-9e00-7282cbd6ce64|myDecision|My important decision|1

|===============


如果我们现在部署同一个选择的更新版本，且保持选择的++id++不变，那么选择表中会包含下面的记录：

[options="header"]
|===============
|id|key|name|version
|e29d4126-ed4d-11e6-9e00-7282cbd6ce64|myDecision|My important decision|1
|e9c2a6c0-c085-11e6-9096-6ab56fad108a|myDecision|My important decision|2

|===============

当调用++dmnRuleService.executeDecisionByKey("myDecision")++时，会使用版本++2++的选择定义，因为这是这个选择定义的最新版本。

如果再创建第二个选择，如下定义并部署至Flowable DMN，表中会增加第三行。

[source,xml,linenums]
----
<definitions id="myNewDefinitions" >
  <decision id="myNewDecision" name="My important decision" >
    <decisionTable id="decisionTable1" hitPolicy="FIRST" >
      ...
----

表将显示类似：

[options="header"]
|===============
|id|key|name|version
|e29d4126-ed4d-11e6-9e00-7282cbd6ce64|myDecision|My important decision|1
|e9c2a6c0-c085-11e6-9096-6ab56fad108a|myDecision|My important decision|2
|d317d3f7-e948-11e6-9ce6-b28c070b517d|myNewDecision|My important decision|1

|===============

请注意新选择的key与第一个选择的不同。即使name是相同的（我们可能本应该也改变它），Flowable DMN只用++id++属性来区分选择。因此新的选择部署时版本为1.


[[deploymentCategory]]


=== 类别 Category

DMN部署与选择表都可以定义类别。部署的类别可以这样使用API指定：

[source,java,linenums]
----
dmnRepository
    .createDeployment()
    .category("yourCategory")
    ...
    .deploy();
----

选择表的类别可以这样使用API定义：

[source,java,linenums]
----
dmnRepository.setDecisionTableCategory("e9c2a6c0-c085-11e6-9096-6ab56fad108a", "yourCategory");
----
