
[[restApiChapter]]

== DMN REST API


=== Flowable DMN REST一般原则 General Flowable DMN REST principles


==== 安装与认证 Installation and Authentication

Flowable DMN在DMN引擎中包含了REST API，可以通过在servlet容器如Apache Tomcat中，部署flowable-app-rest.war文件来安装。但是也可以在其他的web应用中使用，只要在你的应用中包含这些servlet及其mapping，并在classpath中添加所有flowable-dmn-rest模块的依赖即可。

默认情况下Flowable DMN引擎连接至一个H2内存数据库。可以修改WEB-INF/classes文件夹下的db.properties文件中的数据库设置。DMN REST API使用JSON格式 (http://www.json.org) ，基于Spring MVC (http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html) 构建。

默认情况下，所有REST资源都需要有一个有效的Flowable已认证用户。我们使用基础HTTP访问认证。因此在请求时，可以在HTTP头添加 __Authorization: BasicXXX==__ ，也可以在请求url中包含用户名与密码（例如__http://username:password@localhost:8080/xyz__）。

**建议使用基础认证时，同时使用HTTPS。**

==== 配置 Configuration

Flowable REST web应用(flowable-app-rest)使用Spring Java Configuration来启动Flowable引擎、定义基础认证安全使用Spring security，以及为特定的变量处理定义变量转换。可以修改WEB-INF/classes目录下的engine.properties文件，定义少量参数。如果需要高级配置选项，可以在flowable-custom-context.xml文件中覆盖默认的Spring bean，这个文件也在WEB-INF/classes目录下。该文件中已经以注释形式提供了示例配置。也可以在这里重载默认的RestResponseFactories。对于DMN引擎来说，就是定义一个新的命名为dmnResponsefactory的Spring bean，使用自定义实现类。

[[restUsageInTomcat]]


==== 在Tomcat中使用 Usage in Tomcat

由于link:$$http://tomcat.apache.org/tomcat-7.0-doc/security-howto.html$$[Tomcat中的默认安全参数]，**默认不能使用已转义斜线符（++%2F++与++%5C++）（返回400结果）。**这可能会影响部署资源与其数据URL，因为URL可能隐含已转义斜线符。

当发现非预期的400结果时，设置下列系统参数：

__-Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true__

最佳实践是（post/put JSON时），在下面描述的HTTP请求中，永远将**Accept**与**Content-Type**头设置为**application/json**。

==== 方法与返回码 Methods and return-codes

.HTTP方法与相应操作
[options="header"]
|===============
|方法|操作
|+GET+|获取单个资源，或获取一组资源。
|+POST+|创建一个新资源。在查询结构太复杂，不能放入GET请求的查询URL中时，也用于执行资源查询。
|+PUT+|更新一个已有资源的参数。也用于在已有资源上的调用动作。
|+DELETE+|删除一个已有资源。

|===============


.HTTP方法响应码
[options="header"]
|===============
|响应|描述
|+200 - Ok+|操作成功，返回响应（++GET++与++PUT++请求）。
|++201 - 已创建++|操作成功，已经创建了实体，并在响应体中返回（++POST++请求）。
|++204 - 无内容++|操作成功，已经删除了实体，因此没有返回的响应体（++DELETE++请求）。
|++401 - 未认证++|操作失败。操作要求设置认证头。如果请求中有认证头，则提供的鉴证并不合法，或者用户未被授权进行该操作。
|++403 - 禁止++|操作被禁止，且不应重试。这不是鉴证或授权的问题，而是说明不允许该操作。例如：删除一个运行中流程的任务是且永远是不允许的，无论该用户或流程/任务的状态。
|++404 - 未找到++|操作失败。请求的资源未找到。
|++405 - 不允许的方法++|操作失败。使用的方法不能用于该资源。例如，更新（PUT）部署资源将导致++405++状态。
|++409 - 冲突++|操作失败。该操作导致更新一个已被其他操作更新的资源，因此本更新不再有效。也可以表明正在为一个集合创建一个资源，但该集合中已经使用了该标识符。
|++415 - 不支持的媒体类型++|操作失败。请求提包含了不支持的媒体类型。也会发生在请求体JSON中包含了未知的属性或值，但没有正确的格式/类型来接受的情况下。
|++500 - 服务器内部错误++|操作失败。执行操作时发生了未知异常。响应体中包含了错误的细节。

|===============

HTTP响应的media-type总是++application/json++，除非请求的是二进制内容（例如部署资源数据）。这时将使用内容的media-type。

==== 错误响应体 Error response body

当发生错误时（客户端与服务器端都可能，4XX及5XX状态码），响应体会包含一个描述了发生的错误的对象。选择未找到时的404状态的例子：

[source,json,linenums]
----
{
  "statusCode" : 404,
  "errorMessage" : "Could not find a decision table with key 'decision1'."
}
----


==== 请求参数 Request parameters


===== URL片段 URL fragments

作为url的一部分的参数（例如，++http://host/flowable-rest/dmn-api/dmn-repository/deployments/{deploymentId}++中的deploymentId参数），如果包含特殊字符，则需要进行合适的转义（参见link:$$https://en.wikipedia.org/wiki/Percent-encoding$$[URL编码或百分号编码]）。大多数框架都内建了这个功能，但要记得考虑它。特别是对可能包含斜线符的段落（例如部署资源），就是必须的。


===== Rest URL查询参数 Rest URL query parameters

作为查询字符串添加在URL中的参数（例如++http://host/flowable-rest/dmn-api/dmn-repository/deployments/?name=Deployment++中的name参数）可以使用下列类型，也会在相应的REST-API文档中提到：

.URL查询参数类型
[options="header"]
|===============
|类型|格式
|String|纯文本参数。可以包含任何URL允许的合法字符。对于++XXXLike++参数，字符串可能会包含通配符++%++（需要进行URL编码）。可以进行like搜索，例如，'Tas%'将匹配所有以'Tas'开头的值。
|Integer|整形参数。只能包含数字型非十进制值（原文如此，下同），在-2.147.483.648至2.147.483.647之间。
|Long|长整形参数。只能包含数字型非十进制值，在-9.223.372.036.854.775.808至9.223.372.036.854.775.807之间。
|Boolean|boolean型参数。可以为++true++或++false++。任何其他值都会导致'++405 - 错误请求++'响应。
|Date|日期型参数。使用ISO-8601日期格式（参考link:$$http://en.wikipedia.org/wiki/ISO_8601$$[wikipedia中的ISO-8601]），使用时间与日期部分（例如++2013-04-03T23:45Z++）。

|===============


[[restJsonBody]]


===== JSON体参数 JSON body parameters

.JSON参数类型
[options="header"]
|===============
|类型|格式
|String|纯文本参数。对于++XXXLike++参数，字符串可能会包含通配符++%++。可以进行like搜索。例如，'Tas%'将匹配所有以'Tas'开头的值。
|Integer|整形参数，使用JSON数字。只能包含数字型非十进制值（原文如此，下同），在-2.147.483.648至2.147.483.647之间。
|Long|长整形参数，使用JSON数字。只能包含数字型非十进制值，在-9.223.372.036.854.775.808至9.223.372.036.854.775.807之间。
|Date|日期型参数，使用JSON文本。使用ISO-8601日期格式（参考link:$$http://en.wikipedia.org/wiki/ISO_8601$$[wikipedia中的ISO-8601]），使用时间与日期部分（例如++2013-04-03T23:45Z++）。

|===============


[[restPagingAndSort]]


===== 分页与排序 Paging and sorting

分页与排序参数可以作为查询字符串加入URL中（例如++http://host/flowable-rest/dmn-api/dmn-repository/deployments?sort=name++中的name参数）。

.查询变量参数
[options="header"]
|===============
|参数|默认值|描述
|sort|各查询实现不同|排序键的名字，在各查询实现中默认值与可用值都不同。
|order|asc|排序顺序，可以是'asc'（顺序）或'desc'（逆序）。
|start|0|对结果分页的参数。默认结果从0开始。
|size|10|对结果分页的参数。默认大小为10.

|===============


[[restQueryVariable]]


===== JSON查询变量格式 JSON query variable format

[source,json,linenums]
----

{
  "name" : "variableName",
  "value" : "variableValue",
  "operation" : "equals",
  "type" : "string"
}
----


.JSON查询变量参数
[options="header"]
|===============
|参数|必填|描述
|name|否|包含在查询中的变量名。在有些使用'++equals++'的查询中可以为空，查询**任意变量名**为给定值的资源。
|value|是|包含在查询中的变量值，需要使用给定类型的正确格式。
|operator|是|查询使用的操作，可以为下列值：++equals, notEquals, equalsIgnoreCase, notEqualsIgnoreCase, lessThan, greaterThan, lessThanOrEquals, greaterThanOrEquals++与++like++。
|type|否|所用变量的类型。当省略时，会从++value++参数推理类型。任何JSON文本值都认为是++string++类型，JSON boolean值认为是++boolean++类型，JSON数字认为是++long++或++integer++，取决于数字的大小。建议在有疑惑时明确指定类型。其他支持的类型列在下面。

|===============


.默认查询JSON类型
[options="header"]
|===============
|类型名|描述
|string|值处理转换为++java.lang.String++。
|short|值处理转换为++java.lang.Integer++。
|integer|值处理转换为++java.lang.Integer++。
|long|值处理转换为++java.lang.Long++。
|double|值处理转换为++java.lang.Double++。
|boolean|值处理转换为++java.lang.Boolean++。
|date|值处理转换为++java.util.Date++。JSON字符串将使用ISO-8601日期格式转换。

|===============


[[restVariables]]

===== 变量表示 Variable representation

当使用变量时（执行选择），读取与写入时REST-api都使用一些通用原则与JSON格式。变量的JSON表示像是这样：

[source,json,linenums]
----
{
  "name" : "variableName",
  "value" : "variableValue",
  "valueUrl" : "http://...",
  "type" : "string"
}
----

.变量的JSON属性
[options="header"]
|===============
|参数|必填|描述
|name|是|变量名。
|value|否|变量的值。当写入变量且省略了++value++时，会使用++null++作为value。
|valueUrl|否|当读取++binary++或++serializable++类型的变量时，这个属性将指向可用于获取原始二进制数据的URL。
|scope|否|变量的范围。如果值为'++local++'，则变量明确定义在其请求的资源上。如果值为'++global++'，则变量定义在其父上（或者父树中的任意父）。当写入变量且省略了scope时，使用++global++。
|type|否|变量的类型。查看下面的表格了解类型的更多信息。当写入变量且省略了这个值时，将使用请求的原始JSON属性类型推断，限制在++string++, ++double++, ++integer++与++boolean++中。建议总是包含类型，以确保不会错误推断类型。
|===============

.变量类型
[options="header"]
|===============
|类型名|描述
|string|值按照++java.lang.String++处理。写入变量时使用原始JSON文本。
|integer|值按照++java.lang.Integer++处理。按约定写入变量时使用JSON数字，失败则退回JSON文本。
|short|值按照++java.lang.Short++处理。按约定写入变量时使用JSON数字，失败则退回JSON文本。
|long|值按照++java.lang.Long++处理。按约定写入变量时使用JSON数字，失败则退回JSON文本。
|double|值按照++java.lang.Double++处理。按约定写入变量时使用JSON数字，失败则退回JSON文本。
|boolean|值按照++java.lang.Boolean++处理。按约定写入变量时使用JSON boolean。
|date|值按照++java.util.Date++处理。写入变量时将转换为ISO-8601日期格式。

|===============

可以使用自定义JSON表示，以支持额外的变量类型（既可以是简单值，也可以是复杂/嵌套的JSON对象）。通过扩展++org.flowable.rest.dmn.service.api.DmnRestResponseFactory++的++initializeVariableConverters()++方法，可以添加额外的++org.flowable.rest.variable.RestVariableConverter++类，来将你的POJO转换为适合通过REST传输的格式，以及将REST值转换为POJO。实际转换JSON使用Jackson。

=== 部署 Deployment

**使用tomcat时，请阅读<<restUsageInTomcat,在Tomcat中使用>>。**


==== DMN部署的列表 List of DMN Deployments

----
GET dmn-repository/deployments
----

.URL查询参数
[options="header"]
|===============
|参数|必填|值|描述
|name|否|String|只返回给定名字的部署。
|nameLike|否|String|只返回名字like给定名字的部署。
|category|否|String|只返回给定分类的部署。
|categoryNotEquals|否|String|只返回不是给定分类的部署。
|tenantId|否|String|只返回给定tenantId的部署。
|tenantIdLike|否|String|只返回tenantId like给定值的部署。
|withoutTenantId|否|Boolean|如果值为++true++，则只返回没有设置tenantId的部署。如果值为++false++，则忽略++withoutTenantId++参数。
|sort|否|'id'（默认）, 'name', 'deploytime'或'tenantId'|用于排序的参数，与'order'一起使用。
|===============

可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。

.REST返回码
[options="header"]
|===============
|返回码|描述
|200|代表请求成功。

|===============

**成功响应体：**

[source,json,linenums]
----
{
  "data": [
    {
      "id": "03ab310d-c1de-11e6-a4f4-62ce84ef239e",
      "name": null,
      "deploymentTime": "2016-12-14T10:16:37.000+01:00",
      "category": null,
      "url": "http://localhost:8080/flowable-rest/dmn-api/dmn-repository/deployments/03ab310d-c1de-11e6-a4f4-62ce84ef239e",
      "parentDeploymentId": "17510",
      "tenantId": ""
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "id",
  "order": "asc",
  "size": 1
}
----


==== 获取一个DMN部署 Get a DMN deployment

----
GET dmn-repository/deployments/{deploymentId}
----

.获取一个部署 - URL参数
[options="header"]
|===============
|参数|必填|值|描述
|deploymentId|是|String|要获取的部署的id。

|===============


.获取一个部署 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到并返回部署。
|404|代表未找到请求的部署。

|===============

**成功响应体：**

[source,json,linenums]
----
{
  "id": "03ab310d-c1de-11e6-a4f4-62ce84ef239e",
  "name": null,
  "deploymentTime": "2016-12-14T10:16:37.000+01:00",
  "category": null,
  "url": "http://localhost:8080/flowable-rest/dmn-api/dmn-repository/deployments/03ab310d-c1de-11e6-a4f4-62ce84ef239e",
  "parentDeploymentId": "17510",
  "tenantId": ""
}
----


==== 创建一个新DMN部署 Create a new DMN deployment

----
POST dmn-repository/deployments
----

**请求体：**

请求体需要包含__multipart/form-data__类型的数据。请求中需要只有一个文件，多余的文件将被忽略。部署名是传入的文件字段的名字。

可以在请求体中传递名为++tenantId++的额外参数（表单字段）。这个字段的值将指定部署所在的租户（tenant）的id。

.创建一个新DMN部署 - 响应码
[options="header"]
|===============
|响应码|描述
|201|代表成功创建部署
|400|代表请求体中没有内容，或部署不支持content的mime-type。状态描述中包含了额外信息。

|===============

**成功响应体：**


[source,json,linenums]
----
{
  "id": "03ab310d-c1de-11e6-a4f4-62ce84ef239e",
  "name": "newDeployment1",
  "deploymentTime": "2016-12-14T10:16:37.000+01:00",
  "category": null,
  "url": "http://localhost:8080/flowable-rest/dmn-api/dmn-repository/deployments/03ab310d-c1de-11e6-a4f4-62ce84ef239e",
  "tenantId" : "myTenant"
}
----


==== 删除一个DMN部署 Delete a DMN deployment

----
DELETE dmn-repository/deployments/{deploymentId}
----

.删除一个DMN部署 - URL参数
[options="header"]
|===============
|参数|必填|值|描述
|deploymentId|是|String|要删除的部署的id。

|===============


.删除一个DMN部署 - 响应码
[options="header"]
|===============
|响应码|描述
|204|代表已找到并删除了部署。响应体设置为空。
|404|代表未找到请求的部署。

|===============


==== 获取一个DMN部署的资源内容 Get a DMN deployment resource content

----
GET dmn-repository/deployments/{deploymentId}/resourcedata/{resourceId}
----

.获取一个DMN部署的资源内容 - URL参数
[options="header"]
|===============
|参数|必填|值|描述
|deploymentId|是|String|要获取资源的部署的id。
|resourceId|是|String|要获取的资源的id。**请确保如果包含斜线符，需要对resourceId进行URL编码。例如，使用'ddecisions%2Fmy-decision.dmn'代替'decisions/my-decision.dmn'。**

|===============



.获取一个DMN部署的资源内容 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到部署与资源，并已返回资源。
|404|代表未找到请求的部署，或者该部署中没有给定id的资源。状态描述包含了额外信息。

|===============

**成功响应体：**


响应体将包含所请求资源的二进制资源内容。响应的content-type与资源'mimeType'参数返回的类型相同。同时将设置content-disposition头，让浏览器可以下载文件而不是直接显示。

=== 选择表 Decision Tables


==== 选择表的列表 List of decision tables


----
GET dmn-repository/decision-tables
----

.选择表的列表 - URL参数
[options="header"]
|===============
|参数|必填|值|描述
|version|否|integer|只返回给定版本的选择表。
|name|否|String|只返回给定名字的选择表。
|nameLike|否|String|只返回名字like给定名字的选择表。
|key|否|String|只返回给定key的选择表。
|keyLike|否|String|只返回key like给定key的选择表。
|resourceName|否|String|只返回给定资源名的选择表。
|resourceNameLike|否|String|只返回资源名like给定资源名的选择表。
|category|否|String|只返回给定分类的选择表
|categoryLike|否|String|只返回分类名like给定名字的选择表。
|categoryNotEquals|否|String|只返回不是给定分类的选择表。
|deploymentId|否|String|只返回给定id的部署中的选择表。
|latest|否|Boolean|只返回选择表的最新版本。只能与'key'及'keyLike'参数一起使用，同时使用任何其它参数都将导致400响应。
|sort|否|'name'（默认）, 'id', 'key', 'category', 'deploymentId'与'version'|用于排序的参数，与'order'一起使用。

|===============

可以在这个URL中使用通用<<restPagingAndSort,分页与排序查询参数>>。



.选择表的列表 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表请求成功，并已返回选择表。
|400|代表某个参数格式错误，或者'latest'与'key', 'keyLike'以外的其他参数一起使用。状态描述中包含了额外信息。

|===============


**成功响应体：**

[source,json,linenums]
----
{
  "data": [
        {
      "id": "46b0379c-c0a1-11e6-bc93-6ab56fad108a",
      "url": "http://localhost:8080/flowable-rest/dmn-api/dmn-repository/decision-tables/46b0379c-c0a1-11e6-bc93-6ab56fad108a",
      "category": null,
      "name": "Decision Table One",
      "key": "DecisionTableOne",
      "description": null,
      "version": 3,
      "resourceName": "dmn-DecisionTableOne.dmn",
      "deploymentId": "46aa6b3a-c0a1-11e6-bc93-6ab56fad108a",
      "parentDeploymentId": "5001",
      "tenantId": ""
    }
  ],
  "total": 1,
  "start": 0,
  "sort": "name",
  "order": "asc",
  "size": 1
}
----


==== 获取一个选择表 Get a decision table

----
GET dmn-repository/decision-tables/{decisionTableId}
----

.获取一个选择表 - URL参数
[options="header"]
|===============
|参数|必填|值|描述
|decisionTableId|是|String|要获取的选择表的id。

|===============


.获取一个选择表 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到并已返回选择表。
|404|代表未找到请求的选择表。
|===============


**成功响应体：**

[source,json,linenums]
----
{
  "id": "46b0379c-c0a1-11e6-bc93-6ab56fad108a",
  "url": "http://localhost:8080/flowable-rest/dmn-api/dmn-repository/decision-tables/46b0379c-c0a1-11e6-bc93-6ab56fad108a",
  "category": null,
  "name": "Decision Table One",
  "key": "DecisionTableOne",
  "description": null,
  "version": 3,
  "resourceName": "dmn-DecisionTableOne.dmn",
  "deploymentId": "46aa6b3a-c0a1-11e6-bc93-6ab56fad108a",
  "parentDeploymentId": "5001",
  "tenantId": ""
}
----


==== 获取一个选择表资源的内容 Get a decision table resource content

----
GET dmn-repository/decision-tables/{decisionTableId}/resourcedata
----

.获取一个选择表资源的内容 - URL参数
[options="header"]
|===============
|参数|必填|值|描述
|decisionTableId|是|String|要获取资源数据的选择表的id。

|===============

**响应：**

与++GET dmn-repository/deployment/{deploymentId}/resourcedata/{resourceId}++完全一样的响应码/响应体。


==== 获取一个选择表的DMN模型 Get a decision table DMN model

----
GET dmn-repository/decision-tables/{decisionTableId}/model
----

.获取一个选择表的DMN模型 - URL参数
[options="header"]
|===============
|参数|必填|值|描述
|decisionTableId|是|String|要获取模型的选择表的id。

|===============


.获取一个选择表的DMN模型 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已找到选择表，并已返回模型。
|404|代表未找到请求的选择表。

|===============


**响应体：**响应体是一个代表了++org.flowable.dmn.model.DmnDefinition++的JSON，包含完整的DMN定义模型。

[source,json,linenums]
----
{
   "processes":[
      {
         "id":"oneTaskProcess",
         "xmlRowNumber":7,
         "xmlColumnNumber":60,
         "extensionElements":{

         },
         "name":"The One Task Process",
         "executable":true,
         "documentation":"One task process description",

         ...
      }
   ]
}
----


=== 选择执行器 Decision Executor


==== 执行一个选择 Execute a decision

----
POST dmn-rule/decision-executor
----

**请求体：**

请求体需要包含__multipart/form-data__类型的数据。需要提供decisionKey。可选提供tenantId和inputVariables(rest变量)的map。


**响应体：**

[source,json,linenums]
----
{
  "resultVariables": [
    {
      "name": "output1",
      "type": "string",
      "value": "was option two"
    }
  ],
  "url": "http://localhost:8080/flowable-rest/dmn-api/rules/decision-executor"
}
----


=== 引擎 Engine


==== 获取DMN引擎信息 Get DMN engine info

----
GET dmn-management/engine
----

返回在REST服务中使用的，DMN引擎的只读视图。


**成功响应体：**

[source,json,linenums]
----
{
   "name":"default",
   "version":"6.0.1",
   "resourceUrl":"file://flowable-dmn/flowable.dmn.cfg.xml",
   "exception":null
}
----

.获取DMN引擎信息 - 响应码
[options="header"]
|===============
|响应码|描述
|200|代表已返回引擎信息。

|===============
